# Generated by Django 4.0.4 on 2022-04-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availible',
            new_name='is_available',
        ),
    ]
